= Vogella Gradle Plugins

This repository is used to provide custom Gradle plugins crafted by the vogella guys

== Vogella AsciiDoctor Plugin

This Gradle Plugin makes use of the http://asciidoctor.org/docs/asciidoctor-gradle-plugin/ in order to create new tutorials on vogella.com

=== Get the Plugin

The root _build.gradle_ file can look like this:

[source, groovy]
----
buildscript {
	repositories { 
		mavenLocal()
		jcenter()
		maven{ url 'https://dl.bintray.com/vogellacompany/Gradle-AsciiDoctor-Plugin/' }
	}
	dependencies {
		classpath 'com.vogella.gradle:com.vogella.gradle.plugin.asciidoc:0.1.0'
	}
}

subprojects {
	apply plugin: 'com.vogella.gradle.plugin'
}
----

=== Create a new tutorial

1. Create a new project(a sub-directory) in the root directory
2. Add the new project to the _settings.gradle_ file (`include '{newProjectName}'`)
3. Open new project in terminal and run `../gradlew cT` to run the `createTemplate` task

=== How to build

In the root directory the following commands can be used to build different outputs.

[source, terminal]
----
// create HTML 5
./gradlew cH

// create PDF
./gradlew cP

// create EPub 3
./gradlew cE

// create All (HTML 5, PDF, EPub 3)
./gradlew cA
----

If these commands are run in the root directory all subprojects will be build.


TIP: Single subprojects can be build when navigating into a subproject and for example run `../gradlew cH`


NOTE: On Windows OS `./gradlew.bat` must be used +
See http://www.vogella.com/tutorials/Gradle/article.html[Gradle tutorial]

=== How to deploy this plugin to Bintray

This plugin makes use of https://github.com/bintray/gradle-bintray-plugin.

[source, terminal]
----
// upload this plugin to bintray
./gradlew bintrayUpload
----

For the upload a _bintrayUser_ and a _bintrayApiKey_ property has to be set in the _gradle.properties_ file. As an alternative a _BINTRAY_USER_ and a _BINTRAY_API_KEY_ has to be set as system property.

In order to test this plugin it can also be published to a local maven repository.

[source, terminal]
----
// deploy the plugin to a local maven repo
./gradlew publishToMavenLocal
----
