:toc:
:toclevels: 1

= Vogella Gradle Plugins

This repository is used to provide custom Gradle plugins crafted by the vogella guys

== Vogella AsciiDoctor Plugin

This Gradle Plugin makes use of the http://asciidoctor.org/docs/asciidoctor-gradle-plugin/ in order to create new tutorials on vogella.com

=== Get the Plugin

The root _build.gradle_ file can look like this:

[source, groovy]
----
buildscript {
	repositories {
		mavenLocal()
		jcenter()
		maven{ url 'https://dl.bintray.com/vogellacompany/Gradle-AsciiDoctor-Plugin/' }
	}
	dependencies {
		classpath 'com.vogella.gradle:com.vogella.gradle.plugin.asciidoc:0.1.0'
	}
}

subprojects {
	apply plugin: 'com.vogella.gradle.plugin'
}
----

=== Create a new tutorial

1. Create a new project(a sub-directory) in the root directory
2. Add the new project to the _settings.gradle_ file (`include '{newProjectName}'`)
3. Open new project in terminal and run `../gradlew cT` to run the `createTemplate` task

When using the _createTemplate_ task a _userName_ property can be specified in the ~/.gradle/_gradle.properties_ file, so that the copyright header directly contains the proper name.

=== How to build

In the root directory the following commands can be used to build different outputs.

[source, terminal]
----
// create HTML 5
./gradlew cH

// create PDF
./gradlew cP

// create EPub 3
./gradlew cE

// create All (HTML 5, PDF, EPub 3)
./gradlew cA
----

If these commands are run in the root directory all subprojects will be build.


TIP: Single subprojects can be build when navigating into a subproject and for example run `../gradlew cH`


NOTE: On Windows OS `./gradlew.bat` must be used +
See http://www.vogella.com/tutorials/Gradle/article.html[Gradle tutorial]

=== How to deploy this plugin to Bintray

This plugin makes use of https://github.com/bintray/gradle-bintray-plugin.

[source, terminal]
----
// upload this plugin to bintray
./gradlew bintrayUpload
----

To publish this plugin you need a Bintray account that is part of the Bintray organization https://bintray.com/vogellacompany[vogellacompany].

For the upload a _bintrayUser_ and a _bintrayApiKey_ property has to be set in the _gradle.properties_ file.

The _gradle.properties_ file can usually be found in the user home's _.gradle_ folder and could look similar to this:

[source, properties]
----
org.gradle.daemon=true
userName=Simon Scholz

bintrayUser=simon-scholz
bintrayApiKey=7aab22ddfa6f78b71651ef503f2a8356bb268526
----

As an alternative a _BINTRAY_USER_ and a _BINTRAY_API_KEY_ can be set as system property.

In order to test this plugin it can also be published to a local maven repository.

[source, terminal]
----
// deploy the plugin to a local maven repo
./gradlew publishToMavenLocal
----


== Exercise Cleaner
The Plugin let's you delete exercise solutions from tests.

=== Get the Plugin

The root _build.gradle_ file can look like this:

[source, groovy]
----
buildscript {
	repositories {
		mavenLocal()
		jcenter()
		maven{ url 'https://dl.bintray.com/vogellacompany/Gradle-AsciiDoctor-Plugin/' }
	}
	dependencies {
		classpath 'com.vogella.gradle:com.vogella.gradle.plugin.exercise_cleaner:0.1.0'
	}
}

subprojects {
	apply plugin: 'com.vogella.gradle.plugin'
}
----

=== Using the plugin
By default the plugin expects the solution area to be marked like this:

[source, java]
----
@Test
public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();

    // ------------ START EDITING HERE ----------------------
    classUnderTest.setState(true);
    // ------------ STOP EDITING HERE  ----------------------
    assertTrue("getState should return 'true'", classUnderTest.getState());
}
----

To delete the solution run the gradle task:
[source, terminal]
----
./gradlew clean_exercises
:clean_exercises
Removed 1 solutions from the exercises. Good luck!
----

After that the test should look like this:

[source, java]
----
@Test
public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();

    // ------------ START EDITING HERE ----------------------

    // ------------ STOP EDITING HERE  ----------------------
    assertTrue("getState should return 'true'", classUnderTest.getState());
}
----

=== Changing the RegEx for matching
If you want to change the RegEx that is used for matching you can do this in your `gradle.build` file.

[source, groovy]
----
clean_exercises {
	solutionRegex($/(?sm)(// -{12} START HERE -{22})(.*?)(\s+// -{12} STOP HERE  -{22})/$)
}
----
