== Vogella AsciiDoctor Plugin

This Gradle Plugin makes use of the http://asciidoctor.org/docs/asciidoctor-gradle-plugin/ in order to create new tutorials on vogella.com

=== Get the Plugin

The root _build.gradle_ file can look like this:

[source, groovy]
----
plugins {
    id "com.vogella.asciidoc" version "0.16.0"
}

allprojects {
    apply plugin: 'com.vogella.asciidoc'
}
----

=== Create a new tutorial

Open a terminal in the root tutorial folder and run `./gradlew :cT --name yourProjectsName` to run the `createTemplate` task

When using the _createTemplate_ task a _userName_ property can be specified in the ~/.gradle/_gradle.properties_ file, so that the copyright header directly contains the proper name.

=== How to build

In the root directory the following commands can be used to build different outputs.

[source, terminal]
----
// create HTML 5
./gradlew cH

// create PDF
./gradlew cP

// create EPub 3
./gradlew cE

// create All (HTML 5, PDF, EPub 3)
./gradlew cA
----

If these commands are run in the root directory all subprojects will be build.


TIP: Single subprojects can be build when navigating into a subproject and for example run `../gradlew cH`


NOTE: On Windows OS `./gradlew.bat` must be used +
See http://www.vogella.com/tutorials/Gradle/article.html[Gradle tutorial]

=== How to deploy this plugin to Bintray

This plugin makes use of https://github.com/bintray/gradle-bintray-plugin.

[source, terminal]
----
// upload this plugin to bintray
./gradlew bintrayUpload
----

Execute this command in: 
jnerlich@sol:~/git/com.vogella.gradle.plugins/com.vogella.gradle.plugin.asciidoc$ 

To publish this plugin you need a Bintray account that is part of the Bintray organization https://bintray.com/vogellacompany[vogellacompany].

For the upload a _bintrayUser_ and a _bintrayApiKey_ property has to be set in the _gradle.properties_ file.

The _gradle.properties_ file can usually be found in the user home's _.gradle_ folder and could look similar to this:

[source, properties]
----
org.gradle.daemon=true
userName=Simon Scholz

bintrayUser=simon-scholz
bintrayApiKey=7aab22ddfa6f78b71651ef503f2a8356bb268526
----

As an alternative a _BINTRAY_USER_ and a _BINTRAY_API_KEY_ can be set as system property.

=== How to locally test changes in the plug-in

1. Do the changes e.g. in `/com.vogella.gradle.plugins/com.vogella.gradle.plugin.asciidoc/src/main/groovy/com/vogella/gradle/plugin/AsciiDoc.groovy`

2. Change version number in
`/com.vogella.gradle.plugins/com.vogella.gradle.plugin.asciidoc/build.gradle`, eg., to `0.16.0.dev`

3. Execute in
`/com.vogella.gradle.plugins/com.vogella.gradle.plugin.asciidoc/ `
`./gradlew clean install`

4. Choose the new version number in the tutorials `build.gradle` file
+
[source, groovy]
----
plugins {
  id "com.vogella.asciidoc" version "0.16.0.dev"
}
----
+
5. To test local add mavenLocal() as repository in the tutorials settings.gradle.
   The pluginManagement block has to be placed at the top of the file.
+
[source, groovy]   
----
pluginManagement {
	repositories {
		mavenLocal()
		gradlePluginPortal()
	}
}
----
+
6. e.g. `./gradlew cPB`



